const RepeatSeqSamples = [
  {
    id: 'caesar',
    file: 'samples/caesar/ciphertext.txt',
    text: "ZKHQLQDSULOWKHVZHHWVKRZHUVIDOODQGSLHUFHWKHGURXJKWRIPDUFKWRWKHURRWDQGDOOWKHYHLQVDUHEDWKHGLQOLTXRURIVX" +
      "FKSRZHUDVEULQJVDERXWWKHHQJHQGHULQJRIWKHIORZHUZKHQDOVRCHSKBUXVZLWKKLVVZHHWEUHDWKHAKDOHVDQDLULQHYHUBJU" +
      "RYHDQGKHDWKXSRQWKHWHQGHUVKRRWVDQGWKHBRXQJVXQKLVKDOIFRXUVHLQWKHVLJQRIWKHUDPKDVUXQDQGWKHVPDOOIRZODUHPD" +
      "NLQJPHORGBWKDWVOHHSDZDBWKHQLJKWZLWKRSHQHBHVRQDWXUHSULFNVWKHPDQGWKHLUKHDUWHQJDJHVWKHQSHRSOHORQJWRJRRQ" +
      "SLOJULPDJHVDQGSDOPHUVORQJWRVHHNWKHVWUDQJHUVWUDQGVRIIDURIIVDLQWVKDOORZHGLQVXQGUBODQGVDQGVSHFLDOOBIURP" +
      "HYHUBVKLUHVHQGRIHQJODQGGRZQWRFDQWHUEXUBWKHBZHQGWRVHHNWKHKROBEOLVVIXOPDUWBUTXLFNWRJLYHKLVKHOSWRWKHPZK" +
      "HQWKHBZHUHVLFN"
  },
  {
    id: 'shift',
    file: 'samples/shift/ciphertext.txt',
    text: "MXUDYDQFHYBJXUIMUUJIXEMUHIVQBBQDTFYUHSUJXUTHEKWXJEVCQHSXJEJXUHEEJQDTQBBJXULUYDIQHURQJXUTYDBYGKEHEVIK" +
      "SXFEMUHQIRHYDWIQREKJJXUUDWUDTUHYDWEVJXUVBEMUHMXUDQBIEPUFXOHKIMYJXXYIIMUUJRHUQJXUNXQBUIQDQYHYDULUHOWH" +
      "ELUQDTXUQJXKFEDJXUJUDTUHIXEEJIQDTJXUOEKDWIKDXYIXQBVSEKHIUYDJXUIYWDEVJXUHQCXQIHKDQDTJXUICQBBVEMBQHUCQ" +
      "AYDWCUBETOJXQJIBUUFQMQOJXUDYWXJMYJXEFUDUOUIEDQJKHUFHYSAIJXUCQDTJXUYHXUQHJUDWQWUIJXUDFUEFBUBEDWJEWEED" +
      "FYBWHYCQWUIQDTFQBCUHIBEDWJEIUUAJXUIJHQDWUHIJHQDTIEVVQHEVVIQYDJIXQBBEMUTYDIKDTHOBQDTIQDTIFUSYQBBOVHEC" +
      "ULUHOIXYHUIUDTEVUDWBQDTTEMDJESQDJUHRKHOJXUOMUDTJEIUUAJXUXEBORBYIIVKBCQHJOHGKYSAJEWYLUXYIXUBFJEJXUCMX" +
      "UDJXUOMUHUIYSA"
  },
  {
    id: 'vigenere1',
    file: 'samples/vigenere1/ciphertext.txt',
    text: "HLQBVYEBFVWXTSFHIQHFSSISEDJMZYLRPDVPVOSGSIPFBFKTHBQQMFPSXAHUPVACGLRPOYWXTSIPMZGNCINOGSIPWAWMCIBCSRGH" +
      "NLBCJPVMGOCMZUFLFAIGELQSARIZRRCMZUBQXTSSWSISEHLQBNWWANRALKFHDAUHUSMEGJPIFPEPEFVRILMZRDEZOVCMZSIPVKUE" +
      "ZZQOAOLQOGSYBCAELQHRYHQFFSSAHFLRPHUPCAIARWGBUTWTOYQGAIEDIUBGSIEWTYSRHUPVMAULWDIALRPHUPWYOYWJAKYLVQAN" +
      "VMZUZPPARLELMHFWIQDNHEKHUPRUUUEAUHUZTQBRJIECALXGFRAVUQXDXTSZLRPHUPMDVRLVFSARESSFELQBCPSBZRWSZUGZKACA" +
      "AMXUETQMURDEZRCLPYSEDPABTESESRVXTSFEVMBTPVEHELRPGBQJMFBQJEOVYXEVNWPAKROMZGHYHDMYLRPGNYHEDRNMMZYJJDCZ" +
      "PZQFLDLUFRDIZRBQIZUYLRPRBHRFCPLRFSEMYDMGSIKKRYHFCFPIWHUPLAZLMPUGFQYXANCXKFDFMOYGZKUJRSMEVRWTFCGSIYKU" +
      "PRFVRJAQFRDMOY"
  },
  {
    id: 'vigenere2',
    file: 'samples/vigenere2/ciphertext.txt',
    text: "MEMLESJXEXZIMQPNGYTRDZMVYKRBCGIZJMQMGTSCWGMPWLSIUYLMDZWSCHBZPVVZEVVWSBOEBOPGXXMBQDLCFVUAYIUKGQHRIPSF" +
      "CJPSIZLMEYWRGRZHVRRCRKDKWQSPOHXIWNSLKKRBNRAKYWWXEBWCXFOHGAZJUKTMSDMLQXSUDXRJIKJITRDUSIPWVGKMKGILORRP" +
      "ZJLTHXSDXCBAGWYHPGOMWNYAKGSZRYHYWMKKFMEGHDPPHTKBZYJRRRYAJFBGRIDIDGXTFAAIDZILKOUSOAQADEQJXPWSVNYFWPTS" +
      "QCIKSXIQDVAWEIWNISWIPCXTHDELLYXWGVLCVCGOEYGKRBKKRBCRQQCMWEIVLRYQSNGPDZLYYIDSDCDUSLCSFKWAUBCNDBUNLTKE" +
      "MAXKWASAOPTRJGRLKDYBIVBCNPDYWQUMMNRRFOSIOVWCKERBOEGPLRGSSLWBRQOPINTXBZLMNSKCXRFANMSNIZACSLOBTPSIPUWB" +
      "OOPJUACSYGOGWAAMEJWRHDZHVGRLVOQMXFHNLXHYXPWEWCYSFAAIDZMVYUIWCGCZPGUETBLRIKOFGWRIVCIVWOHRYSWJOTDZXMJX" +
      "WYXQAWVIHJYKSDIBQHSODIVGFWMDXFOYSJRXKUJBZOOCIOMWYEOEDQFQVCZROPPHVKUCWXGCCNBZELHOVXGCMRSBBSPGDTIALSQY" +
      "DRHDPOHEPMFQXFDUWOESRRLMDZWQDHRAYXVGRLKOGSBVHUPRWNYAAKWRCIWOFEOODMLRINBBQADWFXCXLYKPKCVUTWIGWKAXERSA" +
      "UWYHVZYLQSREMYOODMFIMXZOVQRRZLDYVARLWBWRKARIZHHXRAWMYPSGMPSIYOKMFOVCMVDDPVLYSVWYJRRRAKDXZKPTCXSUXPZW" +
      "DWLIETEOXFYQGWYHGKQWFCXPKGSOELHAWMGPVCZROPTRJQIGKDSBOPFUAXWNIUWCWYQRGSPRHKHBGPMLNCOPEIUTWIFNQYURSZFG" +
      "DZILYEIQCRGWMSXZXPWVILQGVKQXKKOMQLCYXNZUKMQMVMHOEROQGABYHTGMKKRBDUSECTRYMBAYRUOPOJPWWOQILOXFOXSUWIQM" +
      "XPLRMQDBCHSIOVWALEHCXGGWYHVKGCJSXWOAHDFWLGWBKFMQENZEKIWNIXJYGCCFQNJTWUKZSZLWSFTWDGLTEBAXKYXQGPFHBORO" +
      "UVEQCVQYTTKKVAZOPNCHGQYHHXWBSXHKYQSNYWHIYZADCRRRJERIQKVMUSTFOEWOZRHUJBZOQMCGKAWPNTSEFMPYCFWYLPPKXPGN" +
      "WYXQRAXSQYXZSDIQDUSQDIRLVMHOERSAUGPCVZSLWMVWZGHDPQHYWIYOWUOASAOXRLMVVZERDRFJDEQJQICOIBEPOPPHJAIAKOWY" +
      "LBIPELHRIVYDLMPGVAVIBHCIFKPWJVBCCISKEBWNWCAHSJNIVGRLLRIGBCCOTXLUREWMELOFHEXEWKXPWUIWVRBCELWNMALYSJRR" +
      "ZLDWWAHMFDWYXQGANYUOXGWXXFEFWWDXVBMAMKPGJRHDPTUUGMKCGPICHKRVDVLGACJYCPWJLXLTKIFNWREQMEYKFREAKSGASCVA" +
      "CWKKPXKEWSXQSNDXDTHUGNIPXFSYFVLZCBZOZGQRBACIFOTPWBMQYASKQXKKQWKDACVYYJZAQIPIKCMAKYAAELRJWIFNHCWBBOEV" +
      "DZIALRISCRCBCISKEBAXKIOLGPZHHIVGHDXFOZSODEJKWEWXICNGCBTRGVEBLOVLCNBZXENKILMMEROQUQPWVKWITYYRDUSHPRJZ" +
      "LWXDLCURMXJEQGPGRSREBRDALXHJWMIEILMRGWYHWNIQJZSQSGWKYAHIEVWCXGWNHAELHQIGDOREDUHDTWWUSTZOPNCFHQOIQZWI" +
      "FNWCMHFEECHTXPMCMYCGGRTWXGPQROXFOCFKNIVYGZQZXMQEOLSCLYJIKMMLKGWJREQJWBMNCGXTQHLWVOGKAZLCBFVAWTVAWCFN" +
      "IPCGOJOQRJIZFCIAEEWPJXKKZQYORCBRQEALHXMAGXIMPGVAXSVZAMDVOLYJBYWEVYMKSVQCDUCZDEQJHMEYRQDEOPPWWNICKOSD" +
      "BRDALXLTKSWIWRYQSYCCSZXPWWIQCNUADAHTIMVDSDSARLLXWKVVKKRBWNYAPHXIEBWNKSOFGADEEUYBLRIJOAUPSSIZLMCOCZIN" +
      "BWWCCOROJOTCKGSZDITAIVUOWYXQHDPMUVSAADMMXJSYLRHYXQEKXCDUSGPCOKROLRXFSFHKZPKKPXKCXSNRBPDEQJWMUEVGDLSJ" +
      "ELXYMIKDWTSFIWWMCKXPWZVMMRGONVBVXWYBENRLWOQEVIMVSDMLQNBZDXXJCQFQGJKFGENGLVLMJCLCVCGQDYQJIZKDELNZCZPV" +
      "QYIKMBMRIGVAGMJKRMJOGGZUSNTWRTIWXDLCWBGPHIOROVGGRAVNGOTGDRQMLRSBCNBZOIPURALBEROFHDPYVKSNJOTCKGWJROHE" +
      "WBGNIABLDPELHSIAKKKCCJSJPIGZSNAXHNKGHACRVGRLEKOCOQIYLXHJKCWCWCCNPKFXWNITWXKRRBTPSINKCJQKRYVLNEYKUKTM" +
      "SDIBCREQPRFKWIFNXFOVFLZWLZMWFGIAKASOEMPGXMLRIIOLZAYKWNXPACXMYYVAWTVYXCVORRCNBZDIFAVQLIILDUIOTEVZWDAC" +
      "YYVVNAELHVVWUOWQMEMLESJXEXZIMQPNGYTRDZMVYKRBCGIZJMQMGTSCWGMPWLSIUYLMDZWSCHBZPVVZEVVWSBOEBOPGXXMBQDLC" +
      "FVUAYIUKGQHRIPSFCJPSIZLMEYWRGRZHVRRCRKDKWQSPOHXIWNSLKKRBNRAKYWWXEBWCXFOHGAZJUKTMSDMLQXSUDXRJIKJITRDU" +
      "SIPWVGKMKGILORRPZJLTHXSDXCBAGWYHPGOMWNYAKGSZRYHYWMKKFMEGHDPPHTKBZYJRRRYAJFBGRIDIDGXTFAAIDZILKOUSOAQA" +
      "DEQJXPWSVNYFWPTSQCIKSXIQDVAWEIWNISWIPCXTHDELLYXWGVLCVCGOEYGKRBKKRBCRQQCMWEIVLRYQSNGPDZLYYIDSDCDUSLCS" +
      "FKWAUBCNDBUNLTKEMAXKWASAOPTRJGRLKDYBIVBCNPDYWQUMMNRRFOSIOVWCKERBOEGPLRGSSLWBRQOPINTXBZLMNSKCXRFANMSN" +
      "IZACSLOBTPSIPUWBOOPJUACSYGOGWAAMEJWRHDZHVGRLVOQMXFHNLXHYXPWEWCYSFAAIDZMVYUIWCGCZPGUETBLRIKOFGWRIVCIV" +
      "WOHRYSWJOTDZXMJXWYXQAWVIHJYKSDIBQHSODIVGFWMDXFOYSJRXKUJBZOOCIOMWYEOEDQFQVCZROPPHVKUCWXGCCNBZELHOVXGC" +
      "MRSBBSPGDTIALSQYDRHDPOHEPMFQXFDUWOESRRLMDZWQDHRAYXVGRLKOGSBVHUPRWNYAAKWRCIWOFEOODMLRINBBQADWFXCXLYKP" +
      "KCVUTWIGWKAXERSAUWYHVZYLQSREMYOODMFIMXZOVQRRZLDYVARLWBWRKARIZHHXRAWMYPSGMPSIYOKMFOVCMVDDPVLYSVWYJRRR" +
      "AKDXZKPTCXSUXPZWDWLIETEOXFYQGWYHGKQWFCXPKGSOELHAWMGPVCZROPTRJQIGKDSBOPFUAXWNIUWCWYQRGSPRHKHBGPMLNCOP" +
      "EIUTWIFNQYURSZFGDZILYEIQCRGWMSXZXPWVILQGVKQXKKOMQLCYXNZUKMQMVMHOEROQGABYHTGMKKRBDUSECTRYMBAYRUOPOJPW" +
      "WOQILOXFOXSUWIQMXPLRMQDBCHSIOVWALEHCXGGWYHVKGCJSXWOAHDFWLGWBKFMQENZEKIWNIXJYGCCFQNJTWUKZSZLWSFTWDGLT" +
      "EBAXKYXQGPFHBOROUVEQCVQYTTKKVAZOPNCHGQYHHXWBSXHKYQSNYWHIYZADCRRRJERIQKVMUSTFOEWOZRHUJBZOQMCGKAWPNTSE" +
      "FMPYCFWYLPPKXPGNWYXQRAXSQYXZSDIQDUSQDIRLVMHOERSAUGPCVZSLWMVWZGHDPQHYWIYOWUOASAOXRLMVVZERDRFJDEQJQICO" +
      "IBEPOPPHJAIAKOWYLBIPELHRIVYDLMPGVAVIBHCIFKPWJVBCCISKEBWNWCAHSJNIVGRLLRIGBCCOTXLUREWMELOFHEXEWKXPWUIW" +
      "VRBCELWNMALYSJRRZLDWWAHMFDWYXQGANYUOXGWXXFEFWWDXVBMAMKPGJRHDPTUUGMKCGPICHKRVDVLGACJYCPWJLXLTKIFNWREQ" +
      "MEYKFREAKSGASCVACWKKPXKEWSXQSNDXDTHUGNIPXFSYFVLZCBZOZGQRBACIFOTPWBMQYASKQXKKQWKDACVYYJZAQIPIKCMAKYAA" +
      "ELRJWIFNHCWBBOEVDZIALRISCRCBCISKEBAXKIOLGPZHHIVGHDXFOZSODEJKWEWXICNGCBTRGVEBLOVLCNBZXENKILMMEROQUQPW" +
      "VKWITYYRDUSHPRJZLWXDLCURMXJEQGPGRSREBRDALXHJWMIEILMRGWYHWNIQJZSQSGWKYAHIEVWCXGWNHAELHQIGDOREDUHDTWWU" +
      "STZOPNCFHQOIQZWIFNWCMHFEECHTXPMCMYCGGRTWXGPQROXFOCFKNIVYGZQZXMQEOLSCLYJIKMMLKGWJREQJWBMNCGXTQHLWVOGK" +
      "AZLCBFVAWTVAWCFNIPCGOJOQRJIZFCIAEEWPJXKKZQYORCBRQEALHXMAGXIMPGVAXSVZAMDVOLYJBYWEVYMKSVQCDUCZDEQJHMEY" +
      "RQDEOPPWWNICKOSDBRDALXLTKSWIWRYQSYCCSZXPWWIQCNUADAHTIMVDSDSARLLXWKVVKKRBWNYAPHXIEBWNKSOFGADEEUYBLRIJ" +
      "OAUPSSIZLMCOCZINBWWCCOROJOTCKGSZDITAI"
  },
  {
    id: 'random',
    file: 'samples/random/random.txt',
    text: "EWTIJSTKEOKMKOPVODXPOWORQGKXXLGQCERDJPNTWHIZFSGPJENISCSJGNKIMYTDIMGUXDTJVQQANEHPGBIWXMSBHQWDHUDUAOUO" +
      "FCJXKXYZKHKXSKLREYTYDWUWHUDKAIMJVBVYOJCGEPDPGFUHCJKDFJPZHZJIEIBKNXAOMPYNXBYVWUTEOMAHKLFRTFRGHHTLXQJJ" +
      "CIHRDXQKMOASVSYXVVAWSYDMRYRZIXDJPBVPISOZBIZGLLBJQVPZSFFJAULSLJCLZYTAGQRCFFRKZSQTTDRFRDCTAZOPFHXCCUZZ" +
      "YAHFBKFAMIJBNYMOKBVLZJRFATBOTGQYKPCVHDIHTCOPCAOYGIWJQRGJOWFZJGLMVSYOKGNZTRYDULGLOKBESGQBSQVGRSGFCTSY" +
      "CWMRFXATXBMBNFAWRTFTQQXJUXSIAXAUCEDEUACXAVVDBWSLICDAUGXXDORJZLXIAKLBYGSREWWFEFEIDUQRWPBBWYTZTTMRHOQR" +
      "LXQIXOOVVEMBITCOFVKTJZEYONYCARCBTQGJJLJTTTVZXFWJXZGHHHZMSICDECFMKJMHKDEPLGRENAUXUBNZBDFYHGVLFQLFGIWA" +
      "QSPKDDSBAGXFYIBOAGLOSTVPLNEYPVNIAXAKHCRFYHRQAOGPZFMNUKMWXRBKKLZFARDRZVPLOGGFIVTRIGVOZAUZGLVKVYJFLTVN" +
      "YYFVIKRDHIMCLZTEJIGFCSNAADEMJSPLIFYFTQEWILYILIPIQPNMWQSQOJFWVHHCIAKMJQXRZDNBNGJOFZCLUTAAVVUADQUOUERU" +
      "WXBOZPRORHLWZIYETAMQBVXZPHNOZKPCNVREVOLCBERANLZEALCMUEYRCTKGASWWWFLCBXIJDPFVLJFSRGFOPYDZJTPUCBHFCFYF" +
      "FJXKPMBQESKMSDJRXLMWZKVUVHLTSEBWSOABPNDCBCIMCBGBHIPIMAQIVVNBWIXUMPEGKLYIYNQBUHGTCVQATLMTLWKXYJAUTCWE" +
      "HIFUIMMDSHEBGYLTNTXMQJEYFBMSHFCZCUYWLDCIEWZFBKQCBFNILTYGEGUFTFJQAHLDNJWTOUCYJGLKHSNECQTIZPSBYKMOJTIY" +
      "JUYHVQYTLBFCQSSEQUTEJGHBTXGCRBTIYVPTUMNFHNXFTAAPEZNDWHAVELBROXZVFAFDNSIFZBMNRQUXYXTOZDTKTMVPOOXLMVTJ" +
      "QXARBQZPOICZXVZJYCBQETKLPDIYWWTHRLLHCJHRQLMUKERRRZJFSWSAOXYYFEIXPORGICFEHSTIHKGBLCCGXNKFOLYUMOCPYVFC" +
      "YZFSOSDEYHWTRMUOMIQNMUDCEYMYIQQDGLSJIUJBHLZZTORPUBGHDMVSZSFOMPMHKOSVALZFIYNNFHIVWGFJJOMRGBPNICQYBMXW" +
      "SKRUJUZYOGDMSBWTHCMELFTEUQWAKFQTANNHCQHGVWTJFRQCKJQWHKSNPUYFIKRSMGVMYLXQTUHZBZJWVSOPJNNOHKQWNRLZKTQQ" +
      "OXMCZFMZRRZVODFGLVCTLHNYDVVYFCDUSUIXLOJBICGPFDVYNPZVMALKQRPANPONCSPKOPDSAOAQQQCOEJYSWFLSLFCIEQKPTDIW" +
      "MRKWAMVNOFEJWVFAXGWGDGUSBTYOWPYKWZTRTZPFDELSXRNVQALLDFJJNQVOSOFNUJSNUOKKIQWFSUEBETKMCXGZDNCEZNKRTQQC" +
      "NHYIDDRPSMNCGRJAISXOKGMQCTRUZVXJFETXZMTCFDMXGZHYDMQMNLKTNHQACADZIFITQNZULGDUCWEIPMQZZYOFTFZCXLASAHLM" +
      "WELNMBCRLPOHWTDRQIYADAOVXZDIVUAIPVWZWLANCGDAXUZKBQYAQITPVOTUXQUDPTOIEUMTIFQJOVNGUNVDYBLKUXWEWDSWWGBN" +
      "TXIUEXMUZJUJFWXFBWIWQXEFBVBYAFYLZXMPJHNJXKCEDLRIKZPIIOZSQHWEHWEAGNLHYKQBZFTUFYWSNOJUNBUGWLPQNACTLUFM"
  }
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = RepeatSeqSamples;
}
